### ISSUE TITLE
Finish button not working

### ISSUE THREAD

**Issue by techinpark** [no-comment/AppStore-Connect-Widget#20]
- all key input done but not working finish button. how can i do?

**Comment by mikakruschel** [comment]
Hey, please make sure that you also entered a name for the api key on the page before.

**Comment by techinpark** [comment]
> Hey, please make sure that you also entered a name for the api key on the page before.

yes. all done 😅

**Comment by techinpark** [comment]
@mikakruschel any solutions?

**Comment by mikakruschel** [comment]
The only conditions for the finish button to be disabled are: `name.isEmpty || issuerID.isEmpty || keyID.isEmpty || key.isEmpty || vendor.isEmpty`. So if you have everything filled out there shouldn't be anything stopping you from adding the key. I have added some better error handling (marking empty fields with a red border) and will upload and submit the new build to TestFlight shortly. If you already using ACWidget via [TestFlight](https://testflight.apple.com/join/FrG9FTYt) you will receive the update as soon as the build is reviewed.

**Comment by techinpark** [comment]
Thanks! I looking forward to new build version 😄

**Comment by techinpark** [comment]
@mikakruschel version 1.3 still not working :/

**Comment by mikakruschel** [comment]
What exactly do you mean by the finish button not working? Is it disabled(grayed out) or does nothing happen when you click it?

**Comment by techinpark** [comment]
@mikakruschel nothing happen when click it.

**Comment by mikakruschel** [comment]
Hey @techinpark, I don't know what to do at this point because I can't reproduce any problem 🤷‍♂️. Maybe if you have some time you could clone this repo and debug it yourself.

**Comment by techinpark** [comment]
@mikakruschel  I found the problem and solved it.  when no have access for `Sales and Report`  finish button is not working. 
thanks for good your work!

**Comment by mikakruschel** [comment]
Glad to hear that.

**Comment by Drusy** [comment]
The same happens to me the button is enabled (blue) but the tap does nothing.
No loading, no error, no success.
I think an error message would be nice :)
I chose finance on my key. It should be reports?

**Comment by Drusy** [comment]
After cloning and running the project, I can confirm that the issue is server side, it returns a 500, probably because the account is new

```swift
500
Optional("{\r\n\t\"errors\": [{\r\n\t\t\"status\": \"500\",\r\n\t\t\"code\": \"UNEXPECTED_ERROR\",\r\n\t\t\"title\": \"An unexpected error occurred.\",\r\n\t\t\"detail\": \"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/.\"\r\n\t}]\r\n}")
```

Anyway, I think it would be nice to add
- A loader to the button
- A toast in case of error for EVERY error, even UNKNOWN


Currently, only `invalidCredentials` is managed, and every other error makes the button responseless 
```swift
                let apiErr: APIError = (err as? APIError) ?? .unknown
                if apiErr == .invalidCredentials {
                    alert = .invalidKey
                }
```

**Comment by mikakruschel** [comment]
Hey @Drusy, thanks for investigating this problem! We will fix this issue in our next big update.

**Comment by Drusy** [comment]
Sorry currently travelling I have no time to make a proper pull request.
Looking forward for the next update 😃

**Comment by cameronshemilt** [comment]
Hey @techinpark & @Drusy,

we have rewritten ACWidget completely from the ground up into a new app called Trendly.
You can check it out at [gettrendly.app](https://gettrendly.app). This unfortunately means that we will no longer work on ACWidget.
