### ISSUE TITLE
Widget Shows wrong account data but app works 

### ISSUE THREAD

**Issue by nneubauer** [no-comment/AppStore-Connect-Widget#22]
Since a few weeks, I am getting shown that my account/access data is not correct in the Widget. On the app itself however I can perfectly retrieve everything. I also only have one key. Not sure what the problem is but it used to work fine.

**Comment by mikakruschel** [comment]
Hey, we already edited the widget (for our next big update), such that the widget will try to show older results if an error occurs and the error message is only a small label and doesn't cover everything.
