### ISSUE TITLE
App Bundles not shown

### ISSUE THREAD

**Issue by jacobp100** [no-comment/AppStore-Connect-Widget#24]
If you have an app bundle, this app is not aware of the revenue generated by it

**Comment by cameronshemilt** [comment]
Hey @jacobp100 ,
@mikakruschel and I had a quick look into the issue. Unfortunately neither of us has any app bundles, so it's difficult to test/troubleshoot the problem. We would appreciate the help. A first point to test would be if the bundles are sent by AppStore Connect in the first place. You can download a *Summary Sales Report* in the *Sales and Trends*-tab. This is the exact same data as sent by the API. The product type identifier for bundles are **1-B** and **F1-B**. Do the bundle entries show the correct proceeds?

**Comment by jacobp100** [comment]
This is an excerpt of what I got from the summary report

It looks correct at least

```
Provider	Provider Country	SKU	Developer	Title	Version	Product Type Identifier	Units	Developer Proceeds	Begin Date	End Date	Customer Currency	Country Code	Currency of Proceeds	Apple Identifier	Customer Price	Promo Code	Parent Identifier	Subscription	Period	Category	CMB	Device	Supported Platforms	Proceeds Reason	Preserved Pricing	Client	Order Type
APPLE	US	org.jacob.MusicBundle	Jacob Parker	Super Music Bundle	 	F1-B	1	5.61	01/09/2023	01/15/2023	EUR	BE	EUR	1542101429	7.99	 	 	 	 	Music		iPhone	Mac OS	 	 	 	 
```

**Comment by jacobp100** [comment]
I'm happy to send some real data if it helps - or if you have your work on a branch I can also look into it

**Comment by cameronshemilt** [comment]
Hey @jacobp100,

we have rewritten ACWidget completely from the ground up into a new app called Trendly.
You can check it out at [gettrendly.app](https://gettrendly.app). This unfortunately means that we will no longer work on ACWidget.
