### ISSUE TITLE
UX issues on  Mac

### ISSUE THREAD

**Issue by cool8jay** [no-comment/AppStore-Connect-Widget#27]
1. Setting->Rearrange
It can not drag only one row, instead 6 rows are moved together.
Unless the row is not checked.

<img width="1440" alt="Screenshot 2023-09-19 at 17 02 23 (2)" src="https://github.com/no-comment/AppStore-Connect-Widget/assets/55504/05c8919d-84f5-44ab-97c8-f1dda0d2c300">

2. Home
Mouse wheel can not scroll content.

**Comment by cameronshemilt** [comment]
Hey @cool8jay,

we have rewritten ACWidget completely from the ground up into a new app called Trendly.
You can check it out at [gettrendly.app](https://gettrendly.app). This unfortunately means that we will no longer work on ACWidget.
The UX issue you reported is also fixed there.
